spring:
    application:
      name: bachhoasi
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
    profiles:
        active: ${PENV}
        
aws:
    access:
        key:
            id: ${AWS_ACCESS_ID}
    s3:
        region: ap-southeast-1
        bucket:
            name: ${BUCKET_NAME}
    secret:
        access:
            key: ${AWS_SECRET_ACCESS_KEY}
server:
    servlet:
        context-path: /api/v1
    port: 8080

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
        try-it-out-enabled: true
        operations-sorter: method
        tags-sorter: alpha
        filter: true

base-urls:
    api: ${BASE_URL_API:null}
    front-end: ${ORIGIN_ALLOWED:null}
access-token:
    max-age: ${ACCESS_TOKEN_EXT:86400000}
    secret-key: ${ACCESS_TOKEN_KEY} 

refresh-token:
    max-age: ${REFRESH_TOKEN_EXT:315360000}

app:
    jwtSecret: ${JWT_SECRET}
    jwtExpiration: ${JWT_EXPIRATION}